# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addProject(object):
    def setupUi(self, addProject):
        addProject.setObjectName("addProject")
        addProject.resize(359, 230)
        self.buttonBox = QtWidgets.QDialogButtonBox(addProject)
        self.buttonBox.setGeometry(QtCore.QRect(20, 180, 321, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEditProjectId = QtWidgets.QLineEdit(addProject)
        self.lineEditProjectId.setGeometry(QtCore.QRect(120, 20, 221, 41))
        self.lineEditProjectId.setObjectName("lineEditProjectId")
        self.lineEditClientId = QtWidgets.QLineEdit(addProject)
        self.lineEditClientId.setGeometry(QtCore.QRect(120, 70, 221, 41))
        self.lineEditClientId.setObjectName("lineEditClientId")
        self.lineEditProjectName = QtWidgets.QLineEdit(addProject)
        self.lineEditProjectName.setGeometry(QtCore.QRect(120, 120, 221, 41))
        self.lineEditProjectName.setObjectName("lineEditProjectName")
        self.layoutWidget = QtWidgets.QWidget(addProject)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 120, 101, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.layoutWidget1 = QtWidgets.QWidget(addProject)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 101, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(addProject)
        self.buttonBox.accepted.connect(addProject.accept) # type: ignore
        self.buttonBox.rejected.connect(addProject.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addProject)

    def retranslateUi(self, addProject):
        _translate = QtCore.QCoreApplication.translate
        addProject.setWindowTitle(_translate("addProject", "Add Project"))
        self.label_3.setText(_translate("addProject", "Project Name :"))
        self.label.setText(_translate("addProject", "ID Project :"))
        self.label_2.setText(_translate("addProject", "Client ID :"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     addProject = QtWidgets.QDialog()
#     ui = Ui_addProject()
#     ui.setupUi(addProject)
#     addProject.show()
#     sys.exit(app.exec_())
