# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OptionProjectId.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OptionProject(object):
    def setupUi(self, OptionProject):
        OptionProject.setObjectName("OptionProject")
        OptionProject.resize(291, 103)
        self.scrollArea = QtWidgets.QScrollArea(OptionProject)
        self.scrollArea.setGeometry(QtCore.QRect(20, 20, 261, 31))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 29))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox.setGeometry(QtCore.QRect(0, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setDecimals(0)
        self.doubleSpinBox.setMinimum(22001.0)
        self.doubleSpinBox.setMaximum(30001.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(OptionProject)
        self.pushButton.setGeometry(QtCore.QRect(190, 67, 91, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(OptionProject)
        QtCore.QMetaObject.connectSlotsByName(OptionProject)

    def retranslateUi(self, OptionProject):
        _translate = QtCore.QCoreApplication.translate
        OptionProject.setWindowTitle(_translate("OptionProject", "Option Project ID"))
        self.pushButton.setText(_translate("OptionProject", "Show Sample"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptionProject = QtWidgets.QWidget()
    ui = Ui_OptionProject()
    ui.setupUi(OptionProject)
    OptionProject.show()
    sys.exit(app.exec_())
