# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insertCell.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(737, 697)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(40, 50, 221, 361))
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")

        self.retranslateUi(Form)
        # self.tableWidget.cellPressed['int','int'].connect(self.tableWidget.insertRow) # type: ignore
        self.tableWidget.cellPressed['int', 'int'].connect(self.tambahCell)

        QtCore.QMetaObject.connectSlotsByName(Form)




    def tambahCell(self):

        if((self.tableWidget.currentIndex().row() == self.tableWidget.rowCount()-1)):

            # for i in range(self.tableWidget.rowCount() - 1):
            #     for j in range(self.tableWidget.columnCount() - 1):
            #         if(self.tableWidget.item(i, j) == None):
            #             self.tableWidget.setItem(i, j, QTableWidgetItem().setText(str('')))
            #         else:
            #             item = QTableWidgetItem()
            #             text = str(self.tableWidget.item(i, j).text())
            #             item.setText(text)
            #
            #             self.tableWidget.setItem(i, j, item)

            self.tableWidget.insertRow(self.tableWidget.rowCount())

            self.cetak()


    def cetak(self):
        for i in range(self.tableWidget.rowCount()):
            for j in range(self.tableWidget.columnCount()):
                if(self.tableWidget.item(i, j) == None):
                    print(self.tableWidget.setItem(i, j, QTableWidgetItem().setText(str(''))))
                else:
                    print(self.tableWidget.item(i, j).text())


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
