# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addContainer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addContainer(object):
    def setupUi(self, addContainer):
        addContainer.setObjectName("addContainer")
        addContainer.resize(361, 206)
        self.buttonBox = QtWidgets.QDialogButtonBox(addContainer)
        self.buttonBox.setGeometry(QtCore.QRect(20, 150, 321, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEditContainerId = QtWidgets.QLineEdit(addContainer)
        self.lineEditContainerId.setGeometry(QtCore.QRect(200, 20, 141, 41))
        self.lineEditContainerId.setObjectName("lineEditContainerId")
        self.lineEditWeightContainer = QtWidgets.QLineEdit(addContainer)
        self.lineEditWeightContainer.setGeometry(QtCore.QRect(200, 80, 141, 41))
        self.lineEditWeightContainer.setObjectName("lineEditWeightContainer")
        self.widget = QtWidgets.QWidget(addContainer)
        self.widget.setGeometry(QtCore.QRect(20, 20, 180, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(addContainer)
        self.buttonBox.accepted.connect(addContainer.accept) # type: ignore
        self.buttonBox.rejected.connect(addContainer.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addContainer)

    def retranslateUi(self, addContainer):
        _translate = QtCore.QCoreApplication.translate
        addContainer.setWindowTitle(_translate("addContainer", "Add Container"))
        self.label.setText(_translate("addContainer", "Container ID :"))
        self.label_2.setText(_translate("addContainer", "Weight Container (gr.) :"))

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     addContainer = QtWidgets.QDialog()
#     ui = Ui_addContainer()
#     ui.setupUi(addContainer)
#     addContainer.show()
#     sys.exit(app.exec_())
