# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addPycnometer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addPycnometer(object):
    def setupUi(self, addPycnometer):
        addPycnometer.setObjectName("addPycnometer")
        addPycnometer.resize(359, 313)
        self.buttonBox = QtWidgets.QDialogButtonBox(addPycnometer)
        self.buttonBox.setGeometry(QtCore.QRect(20, 260, 321, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEditRingId = QtWidgets.QLineEdit(addPycnometer)
        self.lineEditRingId.setGeometry(QtCore.QRect(200, 20, 141, 41))
        self.lineEditRingId.setObjectName("lineEditRingId")
        self.lineEditWeightRing = QtWidgets.QLineEdit(addPycnometer)
        self.lineEditWeightRing.setGeometry(QtCore.QRect(200, 80, 141, 41))
        self.lineEditWeightRing.setObjectName("lineEditWeightRing")
        self.lineEditDiameterRing = QtWidgets.QLineEdit(addPycnometer)
        self.lineEditDiameterRing.setGeometry(QtCore.QRect(200, 130, 141, 41))
        self.lineEditDiameterRing.setObjectName("lineEditDiameterRing")
        self.lineEditThickRing = QtWidgets.QLineEdit(addPycnometer)
        self.lineEditThickRing.setGeometry(QtCore.QRect(200, 190, 141, 41))
        self.lineEditThickRing.setObjectName("lineEditThickRing")
        self.layoutWidget = QtWidgets.QWidget(addPycnometer)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 130, 181, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.layoutWidget1 = QtWidgets.QWidget(addPycnometer)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 181, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(addPycnometer)
        self.buttonBox.accepted.connect(addPycnometer.accept) # type: ignore
        self.buttonBox.rejected.connect(addPycnometer.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addPycnometer)

    def retranslateUi(self, addPycnometer):
        _translate = QtCore.QCoreApplication.translate
        addPycnometer.setWindowTitle(_translate("addPycnometer", "Add Pycnometer"))
        self.label_3.setText(_translate("addPycnometer", "Val \"M\" (-) :"))
        self.label_4.setText(_translate("addPycnometer", "Val \"N\" (-) :"))
        self.label.setText(_translate("addPycnometer", "Pycnometer ID :"))
        self.label_2.setText(_translate("addPycnometer", "Weight (gr.) :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addPycnometer = QtWidgets.QDialog()
    ui = Ui_addPycnometer()
    ui.setupUi(addPycnometer)
    addPycnometer.show()
    sys.exit(app.exec_())
