# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addProvingRing.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addProvingRing(object):
    def setupUi(self, addProvingRing):
        addProvingRing.setObjectName("addProvingRing")
        addProvingRing.resize(359, 184)
        self.buttonBox = QtWidgets.QDialogButtonBox(addProvingRing)
        self.buttonBox.setGeometry(QtCore.QRect(20, 140, 321, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEditRingId = QtWidgets.QLineEdit(addProvingRing)
        self.lineEditRingId.setGeometry(QtCore.QRect(200, 20, 141, 41))
        self.lineEditRingId.setObjectName("lineEditRingId")
        self.lineEditWeightRing = QtWidgets.QLineEdit(addProvingRing)
        self.lineEditWeightRing.setGeometry(QtCore.QRect(200, 80, 141, 41))
        self.lineEditWeightRing.setObjectName("lineEditWeightRing")
        self.layoutWidget = QtWidgets.QWidget(addProvingRing)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 181, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(addProvingRing)
        self.buttonBox.accepted.connect(addProvingRing.accept) # type: ignore
        self.buttonBox.rejected.connect(addProvingRing.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addProvingRing)

    def retranslateUi(self, addProvingRing):
        _translate = QtCore.QCoreApplication.translate
        addProvingRing.setWindowTitle(_translate("addProvingRing", "Add Proving Ring"))
        self.label.setText(_translate("addProvingRing", "Proving Ring ID :"))
        self.label_2.setText(_translate("addProvingRing", "Calibration (kg/div) :"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     addProvingRing = QtWidgets.QDialog()
#     ui = Ui_addProvingRing()
#     ui.setupUi(addProvingRing)
#     addProvingRing.show()
#     sys.exit(app.exec_())
