# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mold.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DBMold(object):
    def setupUi(self, DBMold):
        DBMold.setObjectName("DBMold")
        DBMold.setEnabled(True)
        DBMold.resize(621, 562)
        self.layoutWidget = QtWidgets.QWidget(DBMold)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 601, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonClose = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayout.addWidget(self.pushButtonClose, 0, 3, 1, 1)
        self.pushButtonAdd = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.gridLayout.addWidget(self.pushButtonAdd, 0, 0, 1, 1)
        self.pushButtonUpdate = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.gridLayout.addWidget(self.pushButtonUpdate, 0, 1, 1, 1)
        self.pushButtonDelete = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.gridLayout.addWidget(self.pushButtonDelete, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(DBMold)
        self.pushButtonClose.clicked.connect(DBMold.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DBMold)

    def retranslateUi(self, DBMold):
        _translate = QtCore.QCoreApplication.translate
        DBMold.setWindowTitle(_translate("DBMold", "DB Mold"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DBMold", "No. Ring"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DBMold", "Weight (gr)"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DBMold", "Diameter (mm)"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DBMold", "Thickness (mm)"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DBMold", "Volume (mm^3)"))
        self.pushButtonClose.setText(_translate("DBMold", "Close"))
        self.pushButtonAdd.setText(_translate("DBMold", "Add"))
        self.pushButtonUpdate.setText(_translate("DBMold", "Edit"))
        self.pushButtonDelete.setText(_translate("DBMold", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DBMold = QtWidgets.QWidget()
    ui = Ui_DBMold()
    ui.setupUi(DBMold)
    DBMold.show()
    sys.exit(app.exec_())
